In [1]:
import matplotlib.pyplot
import pandas as pd
import numpy as np
%matplotlib inline

In [23]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_boston
df1=load_boston()
df1

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [24]:
x=df1.data
y=df1.target

In [25]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [26]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [27]:
df=pd.DataFrame(df1.data,columns=df1.feature_names)
df['Target']=df1.target
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [28]:
df.shape

(506, 14)

In [29]:
df=df.sample(frac=0.25)

In [30]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [31]:
x

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
370  6.53876   0.0  18.10   1.0  0.631  7.016  97.5  1.2024  24.0  666.0   
140  0.29090   0.0  21.89   0.0  0.624  6.174  93.6  1.6119   4.0  437.0   
176  0.07022   0.0   4.05   0.0  0.510  6.020  47.2  3.5549   5.0  296.0   
244  0.20608  22.0   5.86   0.0  0.431  5.593  76.5  7.9549   7.0  330.0   
156  2.44668   0.0  19.58   0.0  0.871  5.272  94.0  1.7364   5.0  403.0   
..       ...   ...    ...   ...    ...    ...   ...     ...   ...    ...   
206  0.22969   0.0  10.59   0.0  0.489  6.326  52.5  4.3549   4.0  277.0   
458  7.75223   0.0  18.10   0.0  0.713  6.301  83.7  2.7831  24.0  666.0   
239  0.09252  30.0   4.93   0.0  0.428  6.606  42.2  6.1899   6.0  300.0   
320  0.16760   0.0   7.38   0.0  0.493  6.426  52.3  4.5404   5.0  287.0   
220  0.35809   0.0   6.20   1.0  0.507  6.951  88.5  2.8617   8.0  307.0   

     PTRATIO       B  LSTAT  
370     20.2  392.05   2.96  
140     21.2  388.08  24.16  
176     16.6  393.23  10.11  
244     19.1  372.49  12.50  
156     14.7   88.63  16.14  
..       ...     ...    ...  
206     18.6  394.87  10.97  
458     20.2  272.21  16.23  
239     16.6  383.78   7.37  
320     19.6  396.90   7.20  
220     17.4  391.70   9.71  

[126 rows x 13 columns]

In [32]:
y

370    50.0
140    14.0
176    23.2
244    17.6
156    13.1
       ... 
206    24.4
458    14.9
239    23.3
320    23.8
220    26.7
Name: Target, Length: 126, dtype: float64

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [34]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)


In [35]:
x_train

array([[-0.55587937,  0.76729464, -0.88686551, ..., -1.0084413 ,
         0.4213098 , -0.09582621],
       [-0.56400844, -0.47776814, -0.84817211, ...,  0.78223779,
         0.45594009, -0.52998574],
       [-0.55579372,  2.84239928, -1.33630424, ...,  1.67757733,
         0.13910337, -1.04930196],
       ...,
       [-0.56419795, -0.47776814, -1.25445282, ..., -0.41154827,
         0.30724251,  0.00887464],
       [-0.56218619, -0.47776814, -0.95234665, ..., -0.06336067,
         0.42935983, -0.6486467 ],
       [ 1.06170554, -0.47776814,  1.07310407, ...,  0.78223779,
         0.16477231,  0.6300997 ]])

In [36]:
x_test

array([[ 5.99051885e-01, -4.77768140e-01,  1.07310407e+00,
        -2.77350098e-01,  3.13132203e-01,  2.32296003e-01,
         2.10996171e-01, -8.26360618e-01,  1.60907069e+00,
         1.52530426e+00,  7.82237790e-01, -4.08472803e+00,
        -1.47478628e-01],
       [-5.56841518e-01, -4.77768140e-01, -1.30855980e-01,
        -2.77350098e-01, -2.91634100e-02,  7.05275830e-01,
         4.54669873e-01, -5.68948926e-01, -4.18358379e-01,
         1.42463038e-01, -4.11548269e-01,  4.36042863e-01,
        -4.08532751e-01],
       [-5.42600610e-01, -4.77768140e-01, -1.78478627e-01,
        -2.77350098e-01,  3.22383435e-01, -9.99082510e-01,
        -1.43738475e+00, -5.03611353e-01, -4.18358379e-01,
        -9.98296545e-02,  2.84826932e-01,  4.01108804e-01,
         6.30099696e-01],
       [ 5.89771150e-01, -4.77768140e-01,  1.07310407e+00,
        -2.77350098e-01,  3.13132203e-01, -1.96647770e-01,
         1.02085289e+00, -8.23339227e-01,  1.60907069e+00,
         1.52530426e+00,  7.82237790e

In [37]:
from sklearn.neighbors import KNeighborsRegressor

In [38]:
regressor=KNeighborsRegressor(n_neighbors=6,algorithm='auto')
regressor.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=6)

In [39]:
y_pred=regressor.predict(x_test)
y_pred

array([16.8       , 20.53333333, 20.56666667, 14.1       , 22.7       ,
       34.9       , 16.25      , 20.88333333, 16.2       , 24.        ,
       16.86666667, 25.35      , 18.8       , 16.25      , 22.15      ,
       31.9       , 26.53333333, 18.68333333, 17.63333333, 32.01666667,
       11.48333333, 17.08333333, 29.71666667, 19.16666667, 13.3       ,
       20.03333333, 30.51666667, 21.08333333, 17.4       , 20.88333333,
       12.43333333, 18.55      , 19.8       , 29.88333333, 27.35      ,
       15.18333333, 19.4       , 34.56666667, 37.98333333, 13.2       ,
       34.9       , 26.4       ])

In [40]:
from sklearn.metrics import r2_score
score=r2_score(y_pred,y_test)
score

0.12008492302784124

In [41]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [42]:
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.3886010088414794
3.9547619047619045
41.24924603174602
