In [1]:
import seaborn as sns
import pandas as pd
df=pd.read_csv('kc_house_data.csv.zip')
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [2]:
from sklearn.datasets import make_regression

In [3]:
x,y=make_regression(n_samples=1000,n_features=2)

In [4]:
x

array([[ 0.25533195,  0.77560237],
       [-1.14542088, -0.03864231],
       [-0.20606098,  0.18188545],
       ...,
       [-0.41626283, -0.49761777],
       [ 0.65967068, -1.37141793],
       [ 0.09318361, -1.9849672 ]])

In [5]:
y

array([ 7.26099525e+01, -3.87509960e+01,  8.77893866e+00,  4.06324370e+00,
        1.45454400e+02, -5.13180527e+01,  6.69684275e+01, -1.94056688e+01,
        1.01396245e+02,  1.40680138e+02,  1.31037667e+02, -1.06770520e+02,
        2.63308773e+02, -6.43435660e+01,  1.08043106e+01, -7.46594973e+01,
        1.24392407e+02, -3.04875182e+00,  6.00735125e+01, -8.19964080e+01,
       -2.09589165e+01,  7.97577277e+01, -1.61116217e+01,  1.06661755e+02,
       -1.72126872e+02,  1.89172226e+02,  1.04956081e+02, -1.77069742e+02,
       -9.76468507e+01, -2.36680433e+01,  1.72162501e+02, -7.53561338e+01,
        2.03279559e+02,  1.81401465e+00, -2.80112943e+01, -4.28107438e+01,
        7.07255185e+01,  8.91009638e+01,  1.17631331e+01,  7.76814660e+01,
       -1.10334376e+01, -6.30913961e+01,  2.70531863e+01, -1.84223598e+01,
        9.17436892e+01,  4.74253715e+00, -1.17863058e+02, -1.55938244e+01,
       -1.89257629e+02, -5.21741154e+01, -3.69511698e+01, -6.40255624e+01,
       -9.20750222e+01,  

In [6]:
pd.DataFrame(x)[0]

0      0.255332
1     -1.145421
2     -0.206061
3      0.081267
4      0.711599
         ...   
995    0.317565
996    0.673761
997   -0.416263
998    0.659671
999    0.093184
Name: 0, Length: 1000, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=10)

In [8]:
from sklearn.svm import SVR

In [9]:
svr=SVR(kernel='linear')

In [10]:
svr.fit(x_train,y_train)

SVR(kernel='linear')

In [11]:
svr.coef_

array([[31.00760441, 83.35732898]])

In [12]:
y_pred=svr.predict(x_test)

In [13]:
y_pred

array([   3.04458772,   12.13788153,  120.98030859,   22.92098872,
        -67.6082827 ,   63.56983448,   99.00530801,  -44.20482936,
       -106.70439977,  -36.06922995,    1.48936431, -139.16733343,
        -10.59030291,  -15.36405221,   43.45258512,    0.75336369,
         46.34731599,  151.91007686,  -15.56860046,  132.94954629,
        -38.05784032,  -59.72073367,   19.8540577 ,  117.6895114 ,
        -14.12237084,  124.33012891,    6.20829894,   96.92419959,
        -50.93184526,  -31.16371961, -170.60688035,  -68.30425847,
        173.44109601,   72.57469508,  -43.14635788,   65.37307376,
         -2.06354965,   17.4582519 ,  -26.80026707,   92.05845903,
        -49.09123832,   93.39120581,   67.51768765, -145.1173871 ,
         46.16299656, -104.74021962,  -87.35290014,  -66.10060012,
       -117.76898392,   19.58343331, -176.97081768,   -5.12699854,
         42.37073427,  -29.58378556, -231.31501784,   41.76164258,
        -13.66121351,    6.5942117 ,   55.07222444,  -16.09545

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

In [16]:
svr=SVR(kernel='linear')

In [17]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)


In [18]:
svr = SVR(kernel='linear') 

In [19]:
svr.fit(x_train,y_train)

SVR(kernel='linear')

In [20]:
y_pred = svr.predict(X_test_scaled)


In [21]:
y_pred

array([ 3.21290885e+01, -1.47822918e+01,  4.25858699e+01,  6.17199004e+01,
       -6.40955313e+01, -2.19353703e+01, -3.57789882e+01, -6.09990361e+01,
       -2.12732655e+01, -5.24215044e+01, -1.85867180e+02, -2.62585859e+02,
       -2.89328369e+01, -9.38095245e-01, -4.04304677e+01, -5.53684876e+01,
        3.08769771e+01, -7.36040709e+01,  1.17266935e+02,  3.85816984e+01,
       -6.74190190e+01,  3.48073815e+01, -4.48482194e+01, -5.81889900e+01,
        1.13396870e+02, -3.57693686e+01, -5.97976897e+01,  1.62599439e+01,
        2.82233728e+01,  1.08769947e+02, -1.92918076e+02,  1.46174800e+01,
       -7.60395480e+01,  6.39924933e+01,  2.74981322e+02,  4.70493085e+01,
        4.97138949e+01, -1.54523021e+02, -1.26697217e+02, -1.73168466e+02,
        6.27620866e+00,  4.93343654e+01, -8.24098992e+01,  4.83335319e+01,
        8.22684864e+00, -6.70218310e+01, -8.23745823e+01,  1.07286647e+02,
        2.05529635e+02, -5.78815596e+01, -1.77254297e+02,  1.08926945e+01,
        4.87207963e+00,  

In [22]:
from sklearn.metrics import mean_squared_error
import numpy as np


In [23]:
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 36.9748716056983


In [24]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [25]:
from sklearn.model_selection import GridSearchCV

In [26]:
param_grid={'C':[0.1,1,10,100,1000],
           'gamma':[1,0.1,0.01,0.001,0.0001],
            'kernel':['linear']
           }

In [27]:
grid=GridSearchCV(SVR(),param_grid=param_grid,refit=True,cv=5)

In [28]:
grid.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']})

In [29]:
grid.best_params_

{'C': 100, 'gamma': 1, 'kernel': 'linear'}

In [30]:
y_pred_test=svr.predict(x_test)
y_pred_test,y_test

(array([  36.93284272,   -8.92135379,   47.15084389,   65.8713299 ,
         -56.85771147,  -15.76532601,  -29.291131  ,  -53.71469112,
         -15.16870199,  -45.5144595 , -175.92512219, -250.5541566 ,
         -22.54591382,    4.73790181,  -33.79015405,  -48.27590508,
          35.80685985,  -66.10200861,  119.99701404,   43.32191173,
         -60.10890989,   39.45961561,  -37.99831406,  -51.186896  ,
         116.41240636,  -29.33146817,  -52.66435531,   21.57769647,
          33.23004434,  111.85153743, -182.55780774,   19.85880623,
         -68.33227769,   68.09787024,  274.00854093,   51.58120104,
          54.26048759, -145.11572954, -117.99384386, -163.38178005,
          11.75915059,   53.67559145,  -74.72699272,   52.72140272,
          13.62719512,  -59.72004723,  -74.63870796,  110.26078493,
         206.208858  ,  -50.75897185, -167.38595045,   16.29794778,
          10.51197746,   90.64892013,  106.60690233,  172.06596088,
         -73.65903128,  130.96967072,  -90.14588

In [31]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
mse=mean_squared_error(y_test,y_pred_test)
mae=mean_absolute_error(y_test,y_pred_test)
rmse=np.sqrt(mse)
print(mse)
print(mae)
print(rmse)

0.0027426910996546437
0.04205230633155781
0.052370708412762985
